// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dbxfkwfrbotafkjfvvoo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRieGZrd2ZyYm90YWZramZ2dm9vIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI1NjU4NzIsImV4cCI6MjA1ODE0MTg3Mn0.Oq32ip-AwkfG_3JnjrxcNtn4EMUG9RsKjCi1i8E0nmM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);