// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gmtbjsctrkxznobtvdgx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdtdGJqc2N0cmt4em5vYnR2ZGd4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI0NzcwMDQsImV4cCI6MjA1ODA1MzAwNH0.7ZAaWYSP_v61MuSFqwLnnhnW6ZuhZ7pspm6GqbyxzN4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);